project_id = "sigma-nu-scholarship"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 55322
major_version = 17

[studio]
enabled = true
port = 55323

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.external.google]
enabled = false
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
redirect_uri = ""

[local_smtp]
enabled = true
port = 55324
smtp_port = 55325
pop3_port = 55326

[analytics]
enabled = true
port = 55327
backend = "postgres"
